# Container registry for iqsharp
mcr.microsoft.com/quantum/iqsharp-base:0.12.20082513

# Mark that this Dockerfile is used with the samples repository.
# Not sure if needed
# ENV IQSHARP_HOSTING_ENV=SAMPLES_HOSTED

# Make sure the contents of our repo are in ${HOME}.
# These steps are required for use on mybinder.org.
USER root
COPY . ${HOME}
RUN chown -R ${USER} ${HOME}

# Finish by dropping back to the notebook user.
USER ${USER}
